Repository Favor-Gift-Reminder/Favor-Server, pull requests merged in 2023-12, with the labels that each got.

#90 [FIx] GifSimpleDto 필드 추가
  favor/src/main/java/com/favor/favor/friend/FriendService.java
  favor/src/main/java/com/favor/favor/gift/GiftSimpleDto.java
  favor/src/main/java/com/favor/favor/reminder/ReminderSimpleDto.java
  favor/src/main/java/com/favor/favor/user/UserService.java
Labels: 🐞 Bug, 🧹 Clean Up

#92 [FIx] ReminderSimpleDto alarm 값 추가
  favor/src/main/java/com/favor/favor/reminder/ReminderSimpleDto.java
Labels: 🐞 Bug

#93 [Refactor] Friend 일부 리팩터링- #67
  favor/src/main/java/com/favor/favor/friend/Friend.java
  favor/src/main/java/com/favor/favor/friend/FriendController.java
  favor/src/main/java/com/favor/favor/friend/FriendRequestDto.java
  favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java
  favor/src/main/java/com/favor/favor/friend/FriendService.java
  favor/src/main/java/com/favor/favor/gift/GiftService.java
Labels: ♻️ Refactoring

#96 [Fix] 회원 친구목록 조회 시 잘못된 정보 불러오는 문제
  favor/src/main/java/com/favor/favor/user/User.java
  favor/src/main/java/com/favor/favor/user/UserPhotoService.java
  favor/src/main/java/com/favor/favor/user/UserService.java
Labels: 🐞 Bug
