Repository Favor-Gift-Reminder/Favor-Server, pull requests merged in 2023-11, with the labels that each got.

#74 [Fix] 리팩터링 일부 진행
  favor/build.gradle
  favor/src/main/java/com/favor/favor/anniversary/AnniversaryController.java
  favor/src/main/java/com/favor/favor/anniversary/AnniversaryRequestDto.java
  favor/src/main/java/com/favor/favor/anniversary/AnniversaryService.java
  favor/src/main/java/com/favor/favor/common/DefaultResponseDto.java
  favor/src/main/java/com/favor/favor/common/TimeStamped.java
  favor/src/main/java/com/favor/favor/friend/Friend.java
  favor/src/main/java/com/favor/favor/friend/FriendController.java
  favor/src/main/java/com/favor/favor/friend/FriendService.java
  favor/src/main/java/com/favor/favor/gift/Gift.java
  favor/src/main/java/com/favor/favor/gift/GiftController.java
  favor/src/main/java/com/favor/favor/gift/GiftPhotoController.java
  favor/src/main/java/com/favor/favor/gift/GiftPhotoService.java
  favor/src/main/java/com/favor/favor/gift/GiftResponseDto.java
  favor/src/main/java/com/favor/favor/gift/GiftService.java
  favor/src/main/java/com/favor/favor/photo/PhotoService.java
  favor/src/main/java/com/favor/favor/reminder/Reminder.java
  favor/src/main/java/com/favor/favor/reminder/ReminderController.java
  favor/src/main/java/com/favor/favor/reminder/ReminderRequestDto.java
  favor/src/main/java/com/favor/favor/reminder/ReminderService.java
  favor/src/main/java/com/favor/favor/user/User.java
  favor/src/main/java/com/favor/favor/user/UserController.java
  favor/src/main/java/com/favor/favor/user/UserPhotoController.java
  favor/src/main/java/com/favor/favor/user/UserPhotoService.java
  favor/src/main/java/com/favor/favor/user/UserResponseDto.java
  favor/src/main/java/com/favor/favor/user/UserService.java
  favor/src/main/java/com/favor/favor/user/UserUpdatePasswordRequestDto.java
Labels: 🐞 Bug, ♻️ Refactoring

#76 [Fix] 임시 리스트 생성
  favor/src/main/java/com/favor/favor/gift/GiftService.java
Labels: 🐞 Bug

#78 [Fix] 리마인더 리스트 DTO 수정, 친구 nullable 여부 수정
  favor/src/main/java/com/favor/favor/friend/FriendService.java
  favor/src/main/java/com/favor/favor/reminder/Reminder.java
  favor/src/main/java/com/favor/favor/reminder/ReminderController.java
  favor/src/main/java/com/favor/favor/reminder/ReminderRequestDto.java
  favor/src/main/java/com/favor/favor/reminder/ReminderService.java
  favor/src/main/java/com/favor/favor/reminder/ReminderSimpleDto.java
  favor/src/main/java/com/favor/favor/user/UserService.java
Labels: 🐞 Bug

#82 [Fix] 리마인더 수정 시 친구 정보 추가
  favor/src/main/java/com/favor/favor/reminder/ReminderService.java
  favor/src/main/java/com/favor/favor/reminder/ReminderUpdateRequestDto.java
Labels: 🐞 Bug

#84 [Fix] 리마인더 생성과 수정 String pattern 불일치 문제
  favor/src/main/java/com/favor/favor/reminder/ReminderService.java
  favor/src/main/java/com/favor/favor/reminder/ReminderUpdateRequestDto.java
Labels: 🐞 Bug

#85 [Fix] 친구 조회 응답 DTO에 백그라운드 사진 추가
  favor/src/main/java/com/favor/favor/friend/FriendResponseDto.java
Labels: ✨ New Feature

#88 [Fix] 유저간 아이디(닉네임) 중복 허용 문제, 고유값 추가
  favor/src/main/java/com/favor/favor/friend/FriendService.java
  favor/src/main/java/com/favor/favor/friend/FriendSimpleDto.java
  favor/src/main/java/com/favor/favor/gift/GiftService.java
  favor/src/main/java/com/favor/favor/reminder/ReminderService.java
  favor/src/main/java/com/favor/favor/user/UserController.java
  favor/src/main/java/com/favor/favor/user/UserService.java
Labels: 🐞 Bug, 🧹 Clean Up
